Root:
  RFSoC:
    enable: True
    Application:
      AppRingBuffer:
        Adc:
          Ch[:]:
            TrigBurst: 0x0
            ContinuousMode: 0x0
        Dac:
          Ch[:]:
            TrigBurst: 0x0
            ContinuousMode: 0x0
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x0
        BufferLength: 0x1FF
      SigGenLoader:
        enable: True
        Amplitude: '[25000, 0, 0, 0]'
        Decay: '[20e-09, 20e-09, 20e-09, 20e-09]'
        Rise:  '[10e-09, 10e-09, 10e-09, 10e-09]'
        IncidentTime: '[10e-09, 200e-09, 250e-09, 500e-09]'
